// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo38muJcR0_gYFKz9gJ1BQEC1twgHy2tE',
    appId: '1:1022795874212:web:1fd40b8bbe7849fd3acb31',
    messagingSenderId: '1022795874212',
    projectId: 'fypiov',
    authDomain: 'fypiov.firebaseapp.com',
    databaseURL: 'https://fypiov-default-rtdb.firebaseio.com/',
    storageBucket: 'fypiov.firebasestorage.app',
    measurementId: 'G-SX24N81916',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_Yo0SQpxnJAhIDuvxmGpORB07sny9PU',
    appId: '1:1022795874212:android:790a1415172ca6c03acb31',
    messagingSenderId: '1022795874212',
    projectId: 'fypiov',
    databaseURL: 'https://fypiov-default-rtdb.firebaseio.com/',
    storageBucket: 'fypiov.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFXWSoJkyaePGxLnxJrUj9sEZmrT53r-A',
    appId: '1:1022795874212:ios:646a23a846dc903f3acb31',
    messagingSenderId: '1022795874212',
    projectId: 'fypiov',
    databaseURL: 'https://fypiov-default-rtdb.firebaseio.com/',
    storageBucket: 'fypiov.firebasestorage.app',
    iosBundleId: 'com.example.fypapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFXWSoJkyaePGxLnxJrUj9sEZmrT53r-A',
    appId: '1:1022795874212:ios:646a23a846dc903f3acb31',
    messagingSenderId: '1022795874212',
    projectId: 'fypiov',
    databaseURL: 'https://fypiov-default-rtdb.firebaseio.com/',
    storageBucket: 'fypiov.firebasestorage.app',
    iosBundleId: 'com.example.fypapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo38muJcR0_gYFKz9gJ1BQEC1twgHy2tE',
    appId: '1:1022795874212:web:133920caa01722cd3acb31',
    messagingSenderId: '1022795874212',
    projectId: 'fypiov',
    databaseURL: 'https://fypiov-default-rtdb.firebaseio.com/',
    authDomain: 'fypiov.firebaseapp.com',
    storageBucket: 'fypiov.firebasestorage.app',
    measurementId: 'G-FRQWP33QDT',
  );
}
